#!/bin/bash
set -e             # Exit at once if we get any errors
apt-get update
apt-get -y upgrade
apt-get -y dist-upgrade
apt-get install screen avahi-daemon netatalk redis-server minicom
apt-get install sendmail

# Configure Python
sudo apt-get install python3-pip
sudo pip3 install redis
sudo pip3 install pyserial

# Audio dependencies
sudo apt-get install libasound2-dev lame 
